const propiedadesAlquiler = [

  // ── GARAJES ─────────────────────────────────────────────────
  {
    id: 1,
    referencia: "690681",
    tipo: "garaje",
    titulo: "Garaje en Hórreo",
    municipio: "Santiago de Compostela",
    barrio: "Hórreo",
    precio: 70,
    unidad_precio: "mes",
    superficie_construida: 10,
    superficie_extra: null,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: false,
    estado: "reservado",        // "disponible" | "reservado" | "opcion_compra"
    precio_compra: null,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/garage/santiago-de-compostela/horreo/3086/16022362/es/",
    descripcion: "Plaza de garaje en el barrio del Hórreo. Acceso cómodo y seguro.",
    imagen: null,
  },

  {
    id: 2,
    referencia: "755169",
    tipo: "garaje",
    titulo: "Garaje en Ensanche",
    municipio: "Santiago de Compostela",
    barrio: "Ensanche",
    precio: null,               // precio no publicado en listado, solo referencia
    unidad_precio: "mes",
    superficie_construida: 23,
    superficie_extra: null,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: false,
    estado: "disponible",
    precio_compra: 38500,       // también en venta
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/garage/santiago-de-compostela/ensanche/3086/755169/es/",
    descripcion: "Plaza de garaje de 23 m² en el Ensanche. Disponible también en venta.",
    imagen: null,
  },

  // ── ESTUDIOS / PISOS PEQUEÑOS ───────────────────────────────
  {
    id: 3,
    referencia: "753074",
    tipo: "estudio",
    titulo: "Estudio junto al Campus Norte",
    municipio: "Santiago de Compostela",
    barrio: "Campus Norte - S. Caetano",
    precio: 475,
    unidad_precio: "mes",
    superficie_construida: 30,
    superficie_extra: null,
    habitaciones: 1,
    banos: 1,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: false,
    estado: "reservado",
    precio_compra: null,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/studio/santiago-de-compostela/campus-norte-s-caetano/3086/25799314/es/",
    descripcion: "Estudio de 30 m² ideal para estudiantes o trabajadores del Campus Norte.",
    imagen: null,
  },

  // ── PISOS ────────────────────────────────────────────────────
  {
    id: 4,
    referencia: "630486",
    tipo: "piso",
    titulo: "Piso todo exterior en Dormea",
    municipio: "Boimorto",
    barrio: "Dormea",
    precio: 300,
    unidad_precio: "mes",
    superficie_construida: 100,
    superficie_extra: 15,
    habitaciones: 2,
    banos: 1,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: true,
    estado: "reservado",
    precio_compra: null,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/flat/boimorto/dormea/3086/10637693/es/",
    descripcion: "Amplio piso de 100 m² con 15 m² adicionales, todas las habitaciones exteriores. Entorno rural tranquilo.",
    imagen: null,
  },

  {
    id: 5,
    referencia: "350534",
    tipo: "piso",
    titulo: "Piso en Villagarcía de Arousa",
    municipio: "Vilanova de Arousa",
    barrio: "Villagarcía de Arousa",
    precio: 600,
    unidad_precio: "mes",
    superficie_construida: 65,
    superficie_extra: 10,
    habitaciones: 2,
    banos: 1,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: false,
    estado: "reservado",
    precio_compra: null,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/flat/vilanova-de-arousa/villagarcia-de-arousa/3086/2688528/es/",
    descripcion: "Piso de 65 m² con 10 m² adicionales y 2 dormitorios en Villagarcía de Arousa.",
    imagen: null,
  },

  {
    id: 6,
    referencia: "692743",
    tipo: "piso",
    titulo: "Piso todo exterior en Vite",
    municipio: "Santiago de Compostela",
    barrio: "Vite",
    precio: 650,
    unidad_precio: "mes",
    superficie_construida: 89,
    superficie_extra: 6,
    habitaciones: 3,
    banos: 1,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: true,
    estado: "reservado",
    precio_compra: null,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/flat/santiago-de-compostela/vite/3086/16268254/es/",
    descripcion: "Piso de 89 m² totalmente exterior en el barrio de Vite con 3 dormitorios. Luminoso y bien comunicado.",
    imagen: null,
  },

  {
    id: 7,
    referencia: "535147",
    tipo: "piso",
    titulo: "Piso en Galeras",
    municipio: "Santiago de Compostela",
    barrio: "Galeras",
    precio: 700,
    unidad_precio: "mes",
    superficie_construida: 70,
    superficie_extra: null,
    habitaciones: 2,
    banos: 1,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: false,
    estado: "reservado",
    precio_compra: null,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/flat/santiago-de-compostela/galeras/3086/6801301/es/",
    descripcion: "Piso de 70 m² en el barrio de Galeras, zona universitaria con excelente acceso al centro histórico.",
    imagen: null,
  },

  {
    id: 8,
    referencia: "360497",
    tipo: "piso",
    titulo: "Piso con ascensor y terraza en Ensanche",
    municipio: "Santiago de Compostela",
    barrio: "Ensanche",
    precio: 950,
    unidad_precio: "mes",
    superficie_construida: 100,
    superficie_extra: 25,
    habitaciones: 4,
    banos: 2,
    ascensor: true,
    terraza: true,
    amueblado: false,
    exterior: false,
    estado: "reservado",
    precio_compra: null,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/flat/santiago-de-compostela/ensanche/3086/2698467/es/",
    descripcion: "Magnifico piso de 100 m² con 25 m² de terraza, 4 dormitorios y 2 baños en el Ensanche. Con ascensor.",
    imagen: null,
  },

  {
    id: 9,
    referencia: "755170",
    tipo: "piso",
    titulo: "Piso todo exterior — Campus Norte",
    municipio: "Santiago de Compostela",
    barrio: "Campus Norte - S. Caetano",
    precio: 1000,
    unidad_precio: "mes",
    superficie_construida: 75,
    superficie_extra: null,
    habitaciones: 3,
    banos: 1,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: true,
    estado: "disponible",
    precio_compra: null,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/flat/santiago-de-compostela/campus-norte-s-caetano/3086/26369791/es/",
    descripcion: "Luminoso piso de 75 m² con todas las habitaciones al exterior. Ideal para familias o profesionales del Campus Norte.",
    imagen: null,
  },

  {
    id: 10,
    referencia: "759624",
    tipo: "piso",
    titulo: "Piso en el Ensanche",
    municipio: "Santiago de Compostela",
    barrio: "Ensanche",
    precio: 1100,
    unidad_precio: "mes",
    superficie_construida: 107,
    superficie_extra: null,
    habitaciones: 3,
    banos: 2,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: false,
    estado: "disponible",
    precio_compra: null,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/flat/santiago-de-compostela/ensanche/3086/759624/es/",
    descripcion: "Piso de 107 m² en el Ensanche con 3 dormitorios y 2 baños. Zona céntrica y bien comunicada.",
    imagen: null,
  },

  // ── OFICINAS ─────────────────────────────────────────────────
  {
    id: 11,
    referencia: "533008",
    tipo: "oficina",
    titulo: "Oficina en Hórreo — con opción a compra",
    municipio: "Santiago de Compostela",
    barrio: "Hórreo",
    precio: 400,
    unidad_precio: "mes",
    superficie_construida: 35,
    superficie_extra: null,
    habitaciones: 0,
    banos: 1,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: false,
    estado: "opcion_compra",
    precio_compra: 75000,       // precio anterior era 58.000€ (-23%)
    descuento_compra: -23,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/office/santiago-de-compostela/horreo/3086/6712190/es/",
    descripcion: "Oficina de 35 m² en el Hórreo. Disponible también con opción a compra. Precio anterior compra: 58.000 €.",
    imagen: null,
  },

  {
    id: 12,
    referencia: "741977",
    tipo: "oficina",
    titulo: "Oficina en Meixonfrio",
    municipio: "Santiago de Compostela",
    barrio: "Meixonfrio",
    precio: 700,
    unidad_precio: "mes",
    superficie_construida: 160,
    superficie_extra: null,
    habitaciones: 0,
    banos: 2,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: false,
    estado: "disponible",
    precio_compra: null,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/office/santiago-de-compostela/meixonfrio/3086/22228421/es/",
    descripcion: "Amplia oficina de 160 m² con 2 baños en Meixonfrio. Espacios diáfanos, ideal para equipo mediano.",
    imagen: null,
  },

  {
    id: 13,
    referencia: "758422",
    tipo: "oficina",
    titulo: "Oficina representativa en Hórreo — 4 despachos",
    municipio: "Santiago de Compostela",
    barrio: "Hórreo",
    precio: 1900,
    unidad_precio: "mes",
    superficie_construida: 149,
    superficie_extra: null,
    habitaciones: 4,            // despachos
    banos: 2,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: false,
    estado: "disponible",
    precio_compra: null,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/office/santiago-de-compostela/horreo/3086/758422/es/",
    descripcion: "Oficina de 149 m² con 4 despachos independientes en la calle del Hórreo. Ideal para despacho profesional o consultoría.",
    imagen: null,
  },

  // ── LOCALES COMERCIALES ──────────────────────────────────────
  {
    id: 14,
    referencia: "315673",
    tipo: "local",
    titulo: "Local comercial en Pontepedriña — todo exterior",
    municipio: "Santiago de Compostela",
    barrio: "Pontepedriña",
    precio: 550,
    unidad_precio: "mes",
    superficie_construida: 100,
    superficie_extra: null,
    habitaciones: 0,
    banos: 1,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: true,
    estado: "disponible",
    precio_compra: null,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/business-premise/santiago-de-compostela/pontepedrina/3086/2653667/es/",
    descripcion: "Local comercial de 100 m² totalmente exterior en Pontepedriña. Ideal para negocio, taller o uso comercial.",
    imagen: null,
  },

  {
    id: 15,
    referencia: "489276",
    tipo: "local",
    titulo: "Local comercial en el Hórreo",
    municipio: "Santiago de Compostela",
    barrio: "Hórreo",
    precio: 800,
    unidad_precio: "mes",
    superficie_construida: 130,
    superficie_extra: null,
    habitaciones: 0,
    banos: 1,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: false,
    estado: "disponible",
    precio_compra: null,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/business-premise/santiago-de-compostela/horreo/3086/4784430/es/",
    descripcion: "Local de 130 m² en la céntrica calle del Hórreo. Alto tráfico peatonal, perfecto para comercio o clínica.",
    imagen: null,
  },

  {
    id: 16,
    referencia: "750487",
    tipo: "local",
    titulo: "Bajo comercial en Ensanche",
    municipio: "Santiago de Compostela",
    barrio: "Ensanche",
    precio: 1500,
    unidad_precio: "mes",
    superficie_construida: 210,
    superficie_extra: null,
    habitaciones: 0,
    banos: 2,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: false,
    estado: "disponible",
    precio_compra: null,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/flat/santiago-de-compostela/ensanche/3086/750487/es/",
    descripcion: "Gran bajo comercial de 210 m² en el Ensanche. Perfecto para restaurante, academia o gran superficie.",
    imagen: null,
  },

  {
    id: 17,
    referencia: "744234",
    tipo: "local",
    titulo: "Local comercial en Milladoiro",
    municipio: "Ames",
    barrio: "Milladoiro O",
    precio: 2000,
    unidad_precio: "mes",
    superficie_construida: 235,
    superficie_extra: null,
    habitaciones: 0,
    banos: 2,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: false,
    estado: "disponible",
    precio_compra: null,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/business-premise/ames/milladoiro-o/3086/744234/es/",
    descripcion: "Gran local de 235 m² en Milladoiro (Ames). Alta visibilidad y tráfico comercial junto a Santiago. Ideal para franquicia o showroom.",
    imagen: null,
  },

  // ── NAVES INDUSTRIALES ───────────────────────────────────────
  {
    id: 18,
    referencia: "737642",
    tipo: "nave",
    titulo: "Nave industrial en Sionlla",
    municipio: "Santiago de Compostela",
    barrio: "Sionlla",
    precio: 2500,
    unidad_precio: "mes",
    superficie_construida: 1426,
    superficie_extra: null,
    habitaciones: 0,
    banos: 2,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: false,
    estado: "disponible",
    precio_compra: null,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/industrial-unit/santiago-de-compostela/sionlla/3086/737642/es/",
    descripcion: "Gran nave industrial de 1.426 m² en el polígono de Sionlla. Acceso para transporte pesado. Ideal para logística o almacén.",
    imagen: null,
  },

  // ── PROPIEDADES ADICIONALES (página 2) ──────────────────────
  // Nota: la página original tiene 21 props en 2 páginas.
  // Las siguientes son estimadas de la página 2 — verificar en el CRM.
  {
    id: 19,
    referencia: "759624_b",   // pendiente confirmar ref exacta
    tipo: "piso",
    titulo: "Piso en Santiago — pendiente confirmar",
    municipio: "Santiago de Compostela",
    barrio: null,
    precio: null,
    unidad_precio: "mes",
    superficie_construida: null,
    superficie_extra: null,
    habitaciones: null,
    banos: null,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: false,
    estado: "pendiente",       // pendiente de verificar en CRM
    precio_compra: null,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/alquiler.php",
    descripcion: "Propiedad de la página 2 del catálogo. Datos pendientes de confirmar en CRM Inmovilla.",
    imagen: null,
  },

  {
    id: 20,
    referencia: "pendiente_20",
    tipo: "piso",
    titulo: "Piso en Santiago — pendiente confirmar",
    municipio: "Santiago de Compostela",
    barrio: null,
    precio: null,
    unidad_precio: "mes",
    superficie_construida: null,
    superficie_extra: null,
    habitaciones: null,
    banos: null,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: false,
    estado: "pendiente",
    precio_compra: null,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/alquiler.php",
    descripcion: "Propiedad de la página 2 del catálogo. Datos pendientes de confirmar en CRM Inmovilla.",
    imagen: null,
  },

  {
    id: 21,
    referencia: "pendiente_21",
    tipo: "piso",
    titulo: "Piso en Santiago — pendiente confirmar",
    municipio: "Santiago de Compostela",
    barrio: null,
    precio: null,
    unidad_precio: "mes",
    superficie_construida: null,
    superficie_extra: null,
    habitaciones: null,
    banos: null,
    ascensor: false,
    terraza: false,
    amueblado: false,
    exterior: false,
    estado: "pendiente",
    precio_compra: null,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/alquiler.php",
    descripcion: "Propiedad de la página 2 del catálogo. Datos pendientes de confirmar en CRM Inmovilla.",
    imagen: null,
  },

];

// ============================================================
// 🔧 HELPERS — Funciones de uso frecuente sobre el array
// ============================================================

/** Filtra por tipo: "piso" | "estudio" | "garaje" | "local" | "oficina" | "nave" */
const porTipo = (tipo) =>
  propiedadesAlquiler.filter(p => p.tipo === tipo);

/** Solo las disponibles (excluye reservadas y pendientes) */
const soloDisponibles = () =>
  propiedadesAlquiler.filter(p => p.estado === "disponible");

/** Filtra por rango de precio mensual */
const porPrecio = (min, max) =>
  propiedadesAlquiler.filter(p => p.precio >= min && p.precio <= max);

/** Filtra por municipio */
const porMunicipio = (municipio) =>
  propiedadesAlquiler.filter(p =>
    p.municipio && p.municipio.toLowerCase().includes(municipio.toLowerCase())
  );

/** Filtra por mínimo de habitaciones */
const porHabitaciones = (min) =>
  propiedadesAlquiler.filter(p => p.habitaciones >= min);

/** Las que tienen opción a compra */
const conOpcionCompra = () =>
  propiedadesAlquiler.filter(p => p.precio_compra !== null);

// ============================================================
// 📊 ESTADÍSTICAS RÁPIDAS
// ============================================================

const stats = {
  total:       propiedadesAlquiler.length,
  disponibles: soloDisponibles().length,
  reservadas:  propiedadesAlquiler.filter(p => p.estado === "reservado").length,
  precio_min:  Math.min(...propiedadesAlquiler.filter(p => p.precio).map(p => p.precio)),
  precio_max:  Math.max(...propiedadesAlquiler.filter(p => p.precio).map(p => p.precio)),
  tipos: [...new Set(propiedadesAlquiler.map(p => p.tipo))],
  municipios: [...new Set(propiedadesAlquiler.map(p => p.municipio))],
};

export { propiedadesAlquiler, porTipo, soloDisponibles, porPrecio, porMunicipio, porHabitaciones, conOpcionCompra, stats };
