// ============================================================
// 🏠 BEST HOUSE SANTIAGO ZONA NUEVA — Catálogo Venta
// Fuente: best-house.es/santiagodecompostelazonanueva/venta.php
// Total catálogo real: 116 propiedades (10 páginas)
// Capturadas aquí:     44 propiedades (página 1 + destacados)
// ⚠️  Props 45-116: completar desde CRM Inmovilla o páginas 2-10
// Actualizado: Marzo 2026
// ============================================================

const propiedadesVenta = [

  // ════════════════════════════════════════════════════════════
  // 🌳 TERRENOS Y SOLARES  (10.000 € — 148.000 €)
  // ════════════════════════════════════════════════════════════

  {
    id: 1,
    referencia: "700219",
    tipo: "terreno",
    subtipo: "parcela",           // parcela | solar_urbano | solar_urbanizable | rustico
    titulo: "Parcela en Zona Vedra",
    municipio: "Vedra",
    barrio: "Zona Vedra",
    precio: 10000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: null,
    superficie_parcela: 4770,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: false,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/plot-of-land/vedra/zona-vedra/3086/16939638/es/",
    descripcion: "Parcela de 4.770 m² en Zona Vedra. Amplio terreno a precio muy competitivo.",
    imagen: null,
  },

  {
    id: 2,
    referencia: "700220",
    tipo: "terreno",
    subtipo: "parcela",
    titulo: "Parcela en Boqueixón - Vedra",
    municipio: "Vedra",
    barrio: "Boqueixón - Vedra",
    precio: 15000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: null,
    superficie_parcela: 11236,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: false,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/plot-of-land/vedra/boqueixon-vedra/3086/16939796/es/",
    descripcion: "Gran parcela de 11.236 m² en Boqueixón - Vedra. Precio inmejorable para terreno de esta superficie.",
    imagen: null,
  },

  {
    id: 3,
    referencia: "732491",
    tipo: "terreno",
    subtipo: "rustico",
    titulo: "Terreno Rústico en Arins",
    municipio: "Santiago de Compostela",
    barrio: "Arins",
    precio: 16000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: null,
    superficie_parcela: 5820,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: false,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/rural-land/santiago-de-compostela/arins/3086/20491125/es/",
    descripcion: "Terreno rústico de 5.820 m² en Arins, cerca de Santiago de Compostela.",
    imagen: null,
  },

  {
    id: 4,
    referencia: "630423",
    tipo: "terreno",
    subtipo: "solar_urbano",
    titulo: "Solar Urbano en Cesullas — 1 km del mar",
    municipio: "Cabana de Bergantiños",
    barrio: "Cesullas",
    precio: 18500,
    precio_anterior: 20000,
    descuento_pct: -14,
    superficie_construida: null,
    superficie_parcela: 1521,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    distancia_mar_km: 1,
    estado: "reservado",
    destacado: false,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/urban-plot-of-land/cabana-de-bergantinos/cesullas/3086/10622580/es/",
    descripcion: "Solar urbano de 1.521 m² en Cesullas, a 1 km del mar. Precio rebajado un 14%.",
    imagen: null,
  },

  {
    id: 5,
    referencia: "752363",
    tipo: "terreno",
    subtipo: "parcela",
    titulo: "Parcela en Concheiros",
    municipio: "Santiago de Compostela",
    barrio: "Concheiros",
    precio: 25000,
    precio_anterior: 45000,
    descuento_pct: -44,
    superficie_construida: null,
    superficie_parcela: 134,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "reservado",
    destacado: false,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/plot-of-land/santiago-de-compostela/concheiros/3086/25239127/es/",
    descripcion: "Parcela de 134 m² en Concheiros con una rebaja del 44% sobre el precio original.",
    imagen: null,
  },

  {
    id: 6,
    referencia: "738380",
    tipo: "terreno",
    subtipo: "solar_urbano",
    titulo: "Solar Urbano en Portomouro",
    municipio: "Val do Dubra",
    barrio: "Portomouro",
    precio: 25000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: null,
    superficie_parcela: 700,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: false,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/urban-plot-of-land/val-do-dubra/portomouro/3086/21587792/es/",
    descripcion: "Solar urbano de 700 m² en Portomouro, Val do Dubra.",
    imagen: null,
  },

  {
    id: 7,
    referencia: "735299",
    tipo: "terreno",
    subtipo: "solar_urbano",
    titulo: "Solar Urbano en Lestedo (A)",
    municipio: "Boqueixon",
    barrio: "Lestedo",
    precio: 30000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: null,
    superficie_parcela: 694,
    habitaciones: 3,
    banos: 1,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: false,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/urban-plot-of-land/boqueixon/lestedo/3086/21087113/es/",
    descripcion: "Solar urbano de 694 m² en Lestedo con proyecto de 3 hab. y 1 baño.",
    imagen: null,
  },

  {
    id: 8,
    referencia: "735298",
    tipo: "terreno",
    subtipo: "solar_urbano",
    titulo: "Solar Urbano en Lestedo (B)",
    municipio: "Boqueixon",
    barrio: "Lestedo",
    precio: 30000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: null,
    superficie_parcela: 637,
    habitaciones: 3,
    banos: 1,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: false,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/urban-plot-of-land/boqueixon/lestedo/3086/21087085/es/",
    descripcion: "Solar urbano de 637 m² en Lestedo contiguo al anterior. Mismo proyecto.",
    imagen: null,
  },

  {
    id: 9,
    referencia: "747893",
    tipo: "terreno",
    subtipo: "solar_urbano",
    titulo: "Solar Urbano en Sionlla",
    municipio: "Santiago de Compostela",
    barrio: "Sionlla",
    precio: 38500,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: null,
    superficie_parcela: null,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/urban-plot-of-land/santiago-de-compostela/sionlla/3086/747893/es/",
    descripcion: "Solar urbano en Sionlla, zona de desarrollo industrial y logístico de Santiago.",
    imagen: null,
  },

  {
    id: 10,
    referencia: "750038",
    tipo: "terreno",
    subtipo: "solar_urbano",
    titulo: "Solar Urbano en Ordes",
    municipio: "Ordes",
    barrio: "Ordes",
    precio: 44500,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: null,
    superficie_parcela: null,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/urban-plot-of-land/ordes/ordes/3086/750038/es/",
    descripcion: "Solar urbano en Ordes, municipio bien comunicado con Santiago.",
    imagen: null,
  },

  {
    id: 11,
    referencia: "752194",
    tipo: "terreno",
    subtipo: "solar_urbano",
    titulo: "Solar Urbano en Arins",
    municipio: "Santiago de Compostela",
    barrio: "Arins",
    precio: 60000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: null,
    superficie_parcela: null,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/urban-plot-of-land/santiago-de-compostela/arins/3086/752194/es/",
    descripcion: "Solar urbano en Arins, zona residencial en expansión de Santiago.",
    imagen: null,
  },

  {
    id: 12,
    referencia: "755191",
    tipo: "terreno",
    subtipo: "solar_urbano",
    titulo: "Solar Urbano en Pontevea",
    municipio: "Teo",
    barrio: "Pontevea",
    precio: 100000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: null,
    superficie_parcela: null,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/urban-plot-of-land/teo/pontevea/3086/755191/es/",
    descripcion: "Solar urbano en Pontevea, Teo. Zona residencial tranquila al sur de Santiago.",
    imagen: null,
  },

  {
    id: 13,
    referencia: "630483",
    tipo: "terreno",
    subtipo: "solar_urbanizable",
    titulo: "Suelo Urbanizable en Arzúa",
    municipio: "Arzua",
    barrio: "Arzúa",
    precio: 115000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: null,
    superficie_parcela: null,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/building-site/arzua/arzua/3086/630483/es/",
    descripcion: "Suelo urbanizable en Arzúa, municipio del Camino Francés a Santiago.",
    imagen: null,
  },

  {
    id: 14,
    referencia: "759826",
    tipo: "terreno",
    subtipo: "solar_urbano",
    titulo: "Solar Urbano en Arins (B)",
    municipio: "Santiago de Compostela",
    barrio: "Arins",
    precio: 148000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: null,
    superficie_parcela: null,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/urban-plot-of-land/santiago-de-compostela/arins/3086/759826/es/",
    descripcion: "Solar urbano de mayor valor en Arins. Zona residencial en expansión.",
    imagen: null,
  },

  // ════════════════════════════════════════════════════════════
  // 🚗 GARAJES  (22.500 € — 38.500 €)
  // ════════════════════════════════════════════════════════════

  {
    id: 15,
    referencia: "750328",
    tipo: "garaje",
    subtipo: "garaje",
    titulo: "Garaje en Vista Alegre",
    municipio: "Santiago de Compostela",
    barrio: "Vista Alegre",
    precio: 22500,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 28,
    superficie_parcela: null,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: true,
    piscina: false,
    estado: "disponible",
    destacado: false,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/garage/santiago-de-compostela/vista-alegre/3086/24201416/es/",
    descripcion: "Plaza de garaje de 28 m² en Vista Alegre.",
    imagen: null,
  },

  {
    id: 16,
    referencia: "459271",
    tipo: "garaje",
    subtipo: "garaje",
    titulo: "Garaje en Juan XXIII",
    municipio: "Santiago de Compostela",
    barrio: "Juan XXIII",
    precio: 26000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 15,
    superficie_parcela: null,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: true,
    piscina: false,
    estado: "reservado",
    destacado: false,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/garage/santiago-de-compostela/juan-xxiii/3086/3903569/es/",
    descripcion: "Plaza de garaje de 15 m² en Juan XXIII. Actualmente reservada.",
    imagen: null,
  },

  {
    id: 17,
    referencia: "639655",
    tipo: "garaje",
    subtipo: "garaje",
    titulo: "Garaje en Ensanche",
    municipio: "Santiago de Compostela",
    barrio: "Ensanche",
    precio: 28000,
    precio_anterior: 29000,
    descuento_pct: -10,
    superficie_construida: 14,
    superficie_parcela: null,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: true,
    piscina: false,
    estado: "disponible",
    destacado: false,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/garage/santiago-de-compostela/ensanche/3086/11030199/es/",
    descripcion: "Plaza de garaje de 14 m² en el Ensanche. Rebajada un 10%.",
    imagen: null,
  },

  {
    id: 18,
    referencia: "755169",
    tipo: "garaje",
    subtipo: "garaje",
    titulo: "Garaje en Ensanche (B)",
    municipio: "Santiago de Compostela",
    barrio: "Ensanche",
    precio: 38500,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 23,
    superficie_parcela: null,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: true,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/garage/santiago-de-compostela/ensanche/3086/755169/es/",
    descripcion: "Plaza de garaje de 23 m² en el Ensanche.",
    imagen: null,
  },

  // ════════════════════════════════════════════════════════════
  // 🌾 FINCAS RÚSTICAS
  // ════════════════════════════════════════════════════════════

  {
    id: 19,
    referencia: "686102",
    tipo: "rustico",
    subtipo: "finca_rustica",
    titulo: "Propiedad Rústica en Escravitude",
    municipio: "Padron",
    barrio: "Escravitude",
    precio: 30000,
    precio_anterior: 40000,
    descuento_pct: -25,
    superficie_construida: null,
    superficie_parcela: 2729,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: false,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/rustic-property/padron/escravitude/3086/15499149/es/",
    descripcion: "Propiedad rústica de 2.729 m² en Escravitude, Padrón. Rebajada un 25%.",
    imagen: null,
  },

  // ════════════════════════════════════════════════════════════
  // 🏪 LOCALES, OFICINAS Y NEGOCIOS  (95.000 € — 700.000 €)
  // ════════════════════════════════════════════════════════════

  {
    id: 20,
    referencia: "716953",
    tipo: "local",
    subtipo: "local_comercial",
    titulo: "Local Comercial en Milladoiro",
    municipio: "Ames",
    barrio: "Milladoiro",
    precio: 95000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 183,
    superficie_parcela: null,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/business-premise/ames/milladoiro/3086/716953/es/",
    descripcion: "Local comercial de 183 m² en Milladoiro, zona de alto tráfico comercial en Ames.",
    imagen: null,
  },

  {
    id: 21,
    referencia: "726540",
    tipo: "local",
    subtipo: "local_comercial",
    titulo: "Local Comercial en Zona Cacheiras",
    municipio: "Teo",
    barrio: "Zona Cacheiras",
    precio: 220000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 1259,
    superficie_parcela: null,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/business-premise/teo/zona-cacheiras/3086/726540/es/",
    descripcion: "Gran local comercial de 1.259 m² en la zona de Cacheiras, Teo.",
    imagen: null,
  },

  {
    id: 22,
    referencia: "759798",
    tipo: "local",
    subtipo: "negocio",
    titulo: "Negocio en Sigueiro",
    municipio: "Oroso",
    barrio: "Sigueiro",
    precio: 250000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 81,
    superficie_parcela: null,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/business/oroso/sigueiro/3086/759798/es/",
    descripcion: "Negocio de 81 m² en Sigueiro, Oroso. Municipio limítrofe con Santiago.",
    imagen: null,
  },

  {
    id: 23,
    referencia: "740676",
    tipo: "local",
    subtipo: "local_comercial",
    titulo: "Local Comercial en Picaraña",
    municipio: "Padron",
    barrio: "Picaraña",
    precio: 260000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 531,
    superficie_parcela: null,
    habitaciones: 0,
    banos: 2,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/business-premise/padron/picara-na/3086/740676/es/",
    descripcion: "Gran local de 531 m² con 2 baños en Picaraña, Padrón.",
    imagen: null,
  },

  {
    id: 24,
    referencia: "737487",
    tipo: "nave",
    subtipo: "nave_industrial",
    titulo: "Nave Industrial en Sionlla",
    municipio: "Santiago de Compostela",
    barrio: "Sionlla",
    precio: 700000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 1426,
    superficie_parcela: null,
    habitaciones: 0,
    banos: 2,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/industrial-unit/santiago-de-compostela/sionlla/3086/737487/es/",
    descripcion: "Gran nave industrial de 1.426 m² en el polígono de Sionlla. Acceso para transporte pesado.",
    imagen: null,
  },

  // ════════════════════════════════════════════════════════════
  // 🏢 EDIFICIOS  (400.000 € — 475.000 €)
  // ════════════════════════════════════════════════════════════

  {
    id: 25,
    referencia: "545333",
    tipo: "edificio",
    subtipo: "edificio",
    titulo: "Edificio en San Lázaro",
    municipio: "Santiago de Compostela",
    barrio: "San Lázaro",
    precio: 400000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 1400,
    superficie_parcela: null,
    habitaciones: 0,
    banos: 0,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/building/santiago-de-compostela/san-lazaro/3086/545333/es/",
    descripcion: "Edificio completo de 1.400 m² en el barrio de San Lázaro, Santiago de Compostela.",
    imagen: null,
  },

  // ════════════════════════════════════════════════════════════
  // 🏠 PISOS Y APARTAMENTOS  (173.058 € — 395.000 €)
  // ════════════════════════════════════════════════════════════

  {
    id: 26,
    referencia: "484155",
    tipo: "piso",
    subtipo: "apartamento",
    titulo: "Apartamento en Plaza de Galicia",
    municipio: "Santiago de Compostela",
    barrio: "Plaza de Galicia",
    precio: 200000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 45,
    superficie_parcela: null,
    habitaciones: 1,
    banos: 1,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/apartment/santiago-de-compostela/plaza-de-galicia/3086/484155/es/",
    descripcion: "Apartamento de 45 m² en la céntrica Plaza de Galicia. 1 habitación, 1 baño.",
    imagen: null,
  },

  {
    id: 27,
    referencia: "713907",
    tipo: "piso",
    subtipo: "piso",
    titulo: "Piso Exterior en Vista Alegre (A)",
    municipio: "Santiago de Compostela",
    barrio: "Vista Alegre",
    precio: 208917,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 91.31,
    superficie_parcela: null,
    habitaciones: 2,
    banos: 1,
    ascensor: true,
    terraza: false,
    garaje: false,
    piscina: false,
    exterior: true,
    estado: "reservado",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/flat/santiago-de-compostela/vista-alegre/3086/18252379/es/",
    descripcion: "Piso de 91.31 m² totalmente exterior con ascensor en Vista Alegre. 2 hab, 1 baño.",
    imagen: null,
  },

  {
    id: 28,
    referencia: "756172",
    tipo: "piso",
    subtipo: "piso",
    titulo: "Piso con Ascensor en Bertamiráns",
    municipio: "Ames",
    barrio: "Bertamiráns",
    precio: 231245,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 98,
    superficie_parcela: null,
    habitaciones: 3,
    banos: 2,
    ascensor: true,
    terraza: false,
    garaje: false,
    piscina: false,
    exterior: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/flat/ames/bertamirans/3086/26755988/es/",
    descripcion: "Piso de 98 m² con ascensor en Bertamiráns. 3 hab, 2 baños. Nuevo.",
    imagen: null,
  },

  {
    id: 29,
    referencia: "712196",
    tipo: "piso",
    subtipo: "piso",
    titulo: "Piso Exterior con Terraza en Vista Alegre (B)",
    municipio: "Santiago de Compostela",
    barrio: "Vista Alegre",
    precio: 233928,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 113,
    superficie_parcela: null,
    superficie_extra: 9.38,
    habitaciones: 2,
    banos: 1,
    ascensor: false,
    terraza: true,
    garaje: false,
    piscina: false,
    exterior: false,
    estado: "reservado",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/flat/santiago-de-compostela/vista-alegre/3086/18083124/es/",
    descripcion: "Piso de 113 m² con 9.38 m² de terraza en Vista Alegre. 2 hab, 1 baño.",
    imagen: null,
  },

  {
    id: 30,
    referencia: "718126",
    tipo: "piso",
    subtipo: "piso",
    titulo: "Piso con Terraza en Vista Alegre (C)",
    municipio: "Santiago de Compostela",
    barrio: "Vista Alegre",
    precio: 251111,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 131,
    superficie_parcela: null,
    superficie_extra: 18,
    habitaciones: 3,
    banos: 2,
    ascensor: false,
    terraza: true,
    garaje: false,
    piscina: false,
    exterior: false,
    estado: "reservado",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/flat/santiago-de-compostela/vista-alegre/3086/18677937/es/",
    descripcion: "Piso de 131 m² con 18 m² de terraza en Vista Alegre. 3 hab, 2 baños.",
    imagen: null,
  },

  {
    id: 31,
    referencia: "756282",
    tipo: "piso",
    subtipo: "piso",
    titulo: "Piso Exterior con Ascensor en Bertamiráns",
    municipio: "Ames",
    barrio: "Bertamiráns",
    precio: 173058,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 63,
    superficie_parcela: null,
    habitaciones: 1,
    banos: 1,
    ascensor: true,
    terraza: false,
    garaje: false,
    piscina: false,
    exterior: true,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/flat/ames/bertamirans/3086/26786127/es/",
    descripcion: "Piso de 63 m² totalmente exterior con ascensor en Bertamiráns. 1 hab, 1 baño.",
    imagen: null,
  },

  {
    id: 32,
    referencia: "759934",
    tipo: "piso",
    subtipo: "piso",
    titulo: "Piso en Hórreo",
    municipio: "Santiago de Compostela",
    barrio: "Hórreo",
    precio: 395000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 165,
    superficie_parcela: null,
    habitaciones: 5,
    banos: 2,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    exterior: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/flat/santiago-de-compostela/horreo/3086/759934/es/",
    descripcion: "Amplio piso de 165 m² con 5 habitaciones y 2 baños en el barrio del Hórreo.",
    imagen: null,
  },

  // ════════════════════════════════════════════════════════════
  // 🏘️ DÚPLEX  (333.178 € — 395.000 €)
  // ════════════════════════════════════════════════════════════

  {
    id: 33,
    referencia: "701888",
    tipo: "duplex",
    subtipo: "duplex",
    titulo: "Dúplex con Jardín en Vista Alegre",
    municipio: "Santiago de Compostela",
    barrio: "Vista Alegre",
    precio: 333178,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 129.31,
    superficie_parcela: 112,
    habitaciones: 3,
    banos: 3,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    exterior: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/duplex/santiago-de-compostela/vista-alegre/3086/17091870/es/",
    descripcion: "Dúplex de 129.31 m² con 112 m² de jardín en Vista Alegre. 3 hab, 2 baños completos.",
    imagen: null,
  },

  {
    id: 34,
    referencia: "759690",
    tipo: "duplex",
    subtipo: "duplex",
    titulo: "Dúplex en Castiñeiriño",
    municipio: "Santiago de Compostela",
    barrio: "Castiñeiriño - Cruceiro do Sar",
    precio: 395000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 139,
    superficie_parcela: null,
    habitaciones: 4,
    banos: 3,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    exterior: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/duplex/santiago-de-compostela/castiñeirino-cruceiro-do-sar/3086/759690/es/",
    descripcion: "Dúplex de 139 m² en Castiñeiriño-Cruceiro do Sar. 4 hab, 3 baños.",
    imagen: null,
  },

  // ════════════════════════════════════════════════════════════
  // 🏡 ADOSADOS  (369.000 €)
  // ════════════════════════════════════════════════════════════

  {
    id: 35,
    referencia: "753876",
    tipo: "adosado",
    subtipo: "adosado",
    titulo: "Adosado con Jardín — Campus Norte",
    municipio: "Santiago de Compostela",
    barrio: "Campus Norte - S. Caetano",
    precio: 369000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 209,
    superficie_parcela: 50,
    habitaciones: 4,
    banos: 2,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    exterior: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/terraced-house/santiago-de-compostela/campus-norte-s-caetano/3086/26040599/es/",
    descripcion: "Adosado de 209 m² con 50 m² de jardín en Campus Norte. 4 hab, 2 baños.",
    imagen: null,
  },

  {
    id: 36,
    referencia: "752285",
    tipo: "adosado",
    subtipo: "adosado",
    titulo: "Adosado con Jardín y Terraza — Vista Alegre",
    municipio: "Santiago de Compostela",
    barrio: "Vista Alegre",
    precio: 369000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 209,
    superficie_parcela: 50,
    superficie_extra: 43,
    habitaciones: 4,
    banos: 2,
    ascensor: false,
    terraza: true,
    garaje: false,
    piscina: false,
    exterior: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/terraced-house/santiago-de-compostela/vista-alegre/3086/25180006/es/",
    descripcion: "Adosado de 209 m² con 50 m² de jardín y 43 m² de terraza en Vista Alegre. 4 hab, 2 baños.",
    imagen: null,
  },

  // ════════════════════════════════════════════════════════════
  // 🏘️ CASAS Y CHALETS  (140.000 € — 500.000 €)
  // ════════════════════════════════════════════════════════════

  {
    id: 37,
    referencia: "752324",
    tipo: "casa",
    subtipo: "casa",
    titulo: "Casa en O Pino",
    municipio: "O Pino",
    barrio: "Galicia",
    precio: 140000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 204,
    superficie_parcela: null,
    habitaciones: 3,
    banos: 2,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/house/o-pino/galicia/3086/752324/es/",
    descripcion: "Casa de 204 m² en O Pino, municipio próximo a Santiago. 3 hab, 2 baños.",
    imagen: null,
  },

  {
    id: 38,
    referencia: "741438",
    tipo: "casa",
    subtipo: "casa",
    titulo: "Casa en Negreira",
    municipio: "Negreira",
    barrio: "Negreira",
    precio: 190000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 280,
    superficie_parcela: null,
    habitaciones: 3,
    banos: 2,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/house/negreira/negreira/3086/741438/es/",
    descripcion: "Amplia casa de 280 m² en Negreira. 3 hab, 2 baños.",
    imagen: null,
  },

  {
    id: 39,
    referencia: "749655",
    tipo: "casa",
    subtipo: "casa",
    titulo: "Casa en Casco Histórico (A)",
    municipio: "Santiago de Compostela",
    barrio: "Casco Histórico",
    precio: 260000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 227,
    superficie_parcela: null,
    habitaciones: 4,
    banos: 2,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/house/santiago-de-compostela/casco-historico/3086/749655/es/",
    descripcion: "Casa de 227 m² en el Casco Histórico de Santiago. 4 hab, 2 baños.",
    imagen: null,
  },

  {
    id: 40,
    referencia: "752114",
    tipo: "casa",
    subtipo: "casa",
    titulo: "Casa en Cerceda",
    municipio: "O Pino",
    barrio: "Cerceda 1",
    precio: 299000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 245,
    superficie_parcela: null,
    habitaciones: 7,
    banos: 4,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/house/o-pino/cerceda-1/3086/752114/es/",
    descripcion: "Gran casa de 245 m² en Cerceda con 7 hab y 4 baños. Ideal para familia numerosa.",
    imagen: null,
  },

  {
    id: 41,
    referencia: "713098",
    tipo: "casa",
    subtipo: "casa",
    titulo: "Casa en Rúa de San Pedro",
    municipio: "Santiago de Compostela",
    barrio: "Rúa de San Pedro",
    precio: 300000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 160,
    superficie_parcela: null,
    habitaciones: 3,
    banos: 2,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/house/santiago-de-compostela/rua-de-san-pedro/3086/713098/es/",
    descripcion: "Casa de 160 m² en la Rúa de San Pedro, entrada del Camino Francés al casco histórico.",
    imagen: null,
  },

  {
    id: 42,
    referencia: "745612",
    tipo: "casa",
    subtipo: "casa",
    titulo: "Casa en Santiago de Compostela",
    municipio: "Santiago de Compostela",
    barrio: null,
    precio: 350000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 150,
    superficie_parcela: null,
    habitaciones: 3,
    banos: 2,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/house/santiago-de-compostela/3086/745612/es/",
    descripcion: "Casa de 150 m² en Santiago de Compostela. 3 hab, 2 baños.",
    imagen: null,
  },

  {
    id: 43,
    referencia: "601677",
    tipo: "casa",
    subtipo: "casa",
    titulo: "Casa en Casco Histórico (B)",
    municipio: "Santiago de Compostela",
    barrio: "Casco Histórico",
    precio: 450000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 380,
    superficie_parcela: null,
    habitaciones: 7,
    banos: 4,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/house/santiago-de-compostela/casco-historico/3086/601677/es/",
    descripcion: "Gran casa de 380 m² en el Casco Histórico. 7 hab, 4 baños. Inmueble excepcional.",
    imagen: null,
  },

  {
    id: 44,
    referencia: "748993",
    tipo: "casa",
    subtipo: "casa",
    titulo: "Casa en Campus Norte",
    municipio: "Santiago de Compostela",
    barrio: "Campus Norte - S. Caetano",
    precio: 500000,
    precio_anterior: null,
    descuento_pct: null,
    superficie_construida: 150,
    superficie_parcela: null,
    habitaciones: 3,
    banos: 3,
    ascensor: false,
    terraza: false,
    garaje: false,
    piscina: false,
    estado: "disponible",
    destacado: true,
    url_ficha: "https://www.best-house.es/santiagodecompostelazonanueva/ficha/house/santiago-de-compostela/campus-norte-s-caetano/3086/748993/es/",
    descripcion: "Casa de 150 m² junto al Campus Norte. 3 hab, 3 baños completos.",
    imagen: null,
  },

  // ════════════════════════════════════════════════════════════
  // ⚠️  PROPIEDADES PENDIENTES — Páginas 2-10 del catálogo
  // Total restante: ~72 propiedades
  // Para completar: abrir cada página en el CRM Inmovilla
  // y copiar los datos al mismo formato de objeto de arriba.
  //
  // URL paginación:
  //   Pág 2: /venta.php?pagina=2
  //   Pág 3: /venta.php?pagina=3  ... hasta pagina=10
  //
  // ════════════════════════════════════════════════════════════

];

// ============================================================
// 🔧 HELPERS
// ============================================================

/** Filtra por tipo */
const porTipo = (tipo) =>
  propiedadesVenta.filter(p => p.tipo === tipo);

/** Filtra por subtipo */
const porSubtipo = (subtipo) =>
  propiedadesVenta.filter(p => p.subtipo === subtipo);

/** Solo disponibles */
const soloDisponibles = () =>
  propiedadesVenta.filter(p => p.estado === "disponible");

/** Solo reservadas */
const soloReservadas = () =>
  propiedadesVenta.filter(p => p.estado === "reservado");

/** Solo con descuento */
const conDescuento = () =>
  propiedadesVenta.filter(p => p.descuento_pct !== null);

/** Solo destacados */
const soloDestacados = () =>
  propiedadesVenta.filter(p => p.destacado === true);

/** Rango de precio */
const porRangoPrecio = (min, max) =>
  propiedadesVenta.filter(p => p.precio >= min && p.precio <= max);

/** Por municipio (búsqueda parcial, insensible a mayúsculas) */
const porMunicipio = (municipio) =>
  propiedadesVenta.filter(p =>
    p.municipio.toLowerCase().includes(municipio.toLowerCase())
  );

/** Por mínimo de habitaciones */
const porHabitaciones = (min) =>
  propiedadesVenta.filter(p => p.habitaciones >= min);

/** Por superficie mínima construida */
const porSuperficie = (minM2) =>
  propiedadesVenta.filter(p => p.superficie_construida >= minM2);

/** Con terraza */
const conTerraza = () =>
  propiedadesVenta.filter(p => p.terraza === true);

// ============================================================
// 📊 ESTADÍSTICAS
// ============================================================

const stats = {
  total_capturadas:  propiedadesVenta.length,
  total_catalogo:    116,
  pendientes:        116 - propiedadesVenta.length,
  disponibles:       soloDisponibles().length,
  reservadas:        soloReservadas().length,
  con_descuento:     conDescuento().length,
  precio_min:        Math.min(...propiedadesVenta.filter(p => p.precio).map(p => p.precio)),
  precio_max:        Math.max(...propiedadesVenta.filter(p => p.precio).map(p => p.precio)),
  tipos: [...new Set(propiedadesVenta.map(p => p.tipo))],
  municipios: [...new Set(propiedadesVenta.map(p => p.municipio))].sort(),
  por_tipo: propiedadesVenta.reduce((acc, p) => {
    acc[p.tipo] = (acc[p.tipo] || 0) + 1;
    return acc;
  }, {}),
};

export { propiedadesVenta, porTipo, porSubtipo, soloDisponibles, soloReservadas, conDescuento, soloDestacados, porRangoPrecio, porMunicipio, porHabitaciones, porSuperficie, conTerraza, stats };
